
[tool.black]
line-length = 110
target-version = ['py310']


[tool.ruff]
line-length = 110
target-version = 'py310'
ignore = ['F841', 'F401', 'E501']

[tool.ruff.isort]
combine-as-imports = true
force-wrap-aliases = true
known-first-party = ["scripts", "crypto"]
known-third-party = ["modules", "launch"]


[tool.pyright]
exclude = ["../../venv"]
venvPath = "../../"
venv = "venv"
